<?php
//Checkout Constants  markOrderPaid
return [
	'admin_url_prefix'=> 'career/admin',
    'per_page'=>100,
	'js_version'=>'1.0',
	'css_version'=>'1.7.9.5',
	'default_country_code' => 'PK',
	'applicant_prefix' => 'IDS',
	'cgpa_percentage_error' => "The Percentage or CGPA field is required!",
	'files' =>[
		'filetypes' 	=> 'assets/images/icons/filetypes',
		'profile'		=> 'assets/uploads/profile/',
		'cover'			=> 'assets/uploads/cover/',
		'portfolio'		=> 'assets/uploads/portfolio/',
		'familydetail'	=> 'assets/uploads/familydetail/',
		'douments'		=> 'assets/uploads/douments/',
		'tipsandguides' => 'assets/uploads/tipsandguides/'
    ],
	'candidate_documents_tables' => ['candidate_experiences'=>'candidate_experiences','candidate_educations'=>'candidate_educations'],
	'default_document'=>['resume','bank_statement','nic'],
	'required_document'=>[
		'candidate_experiences' =>[1=>['salary_slip'=>'Salary Slip', 'experience_certificate'=>'Experience Certificate']],
		'candidate_educations' =>[
									
									2=>['bachelor_degree'=>'Bachelor Degree', 'bachelor_certificate' =>'Bachelor Certificate'],
									3=>['thesis' =>'Thesis', 'doctorate_degree'=>'Doctorate Degree'],
									4=>['inter_certificate'=>' Inter Certificate', 'inter_provisional'=>'Inter Provisional'],
									5=>['master_degree'=>'Master Degree', 'master_certificate'=>'Master Certificate'],
									6=>['matric_marksheet'=>'Matric Marksheet', 'matric_certificate' =>'Matric Certificate']
								],
	],
	'mobile_code' =>[
		'0300', '0301', '0302', '0303', '0304', '0305', '0306', '0307', '0308', '0309', '0310', '0311', '0312', '0313', '0314', '0315', '0316', '0317', '0318', '0320', 
		'0321', '0322', '0323', '0324', '0325', '0331', '0332', '0333', '0334', '0335', '0336', '0337', '0340', '0341', '0342', '0343', '0344', '0345', '0346', '0347', 
		'0348', '0349', '0355', '0364', '0365', '0581', '03000', '03555'
	],
	'header_show_pages' =>['home','alerts','profile'],
	'months'=>[1 => 'Jan.', 2 => 'Feb.', 3 => 'Mar.', 4 => 'Apr.', 5 => 'May', 6 => 'Jun.', 7 => 'Jul.', 8 => 'Aug.', 9 => 'Sep.', 10 => 'Oct.', 11 => 'Nov.', 12 => 'Dec.'],
	'level_of_educations' => [1=>'A Level',	2=>'Bachelors',3=>'Doctorate',4=>'Intermediate',5=>'Masters',6=>'Matric',7=>'Middle',8=>'O Level'],
	'grades' => ['A+','A','A-','B+','B','B-','C+','C','C-','D','E','F'],
	'o_a_level_grades' =>[0,1,2,3,4,5,6,7,8,9],
	'boards' =>[1=>'Balochistan Board', 2=>'CIE - Cambridge Assessment and/or Edexcel', 3=>'Federal Board of Intermediate and Secondary Education',4=>'General Certificate of Education (GCE) (O/A Levels)',
			5=>'Hyderabad Board',6=>'Karachi Board',7=>'Khyber Pakhtunkhwa Board',8=>'Lahore Board',9=>'other',10=>'Punjab Board',11=>'Sindh Board' ],
	'boolean_options' => [1=>'Yes', 0 =>'No'], 
	'gender_options' => [1=>'Male', 0 =>'Female'],
	'marital_statuses' =>[1=>'Divorced',2=>'Late',3=>'Married',4=>'Single',5=>'Widowed',6=>'Widower'],
	'filter_marital_statuses' =>[3=>'Married',4=>'Single'],
	'file_extension_for_icon' =>['psd','doc','docx','xls','xlsx','zip','rar','ppt','pptx','pdf','mp3'],
	'file_extension_for_resize'=>['jpg','jpeg','png','bmp','gif','svg','webp'],
	'nationality' => [1=>'Pakistani',0=>'Foreign National'],
	'religion' =>[1=>'Atheism and agnosticism', 2=>'Bahá\'í', 3=>'Buddhism', 4=>'Christianity', 5=>'Hinduism', 6=>'Islam', 7=>'Jainism', 8=>'Judaism', 9=>'Kalash', 10=>'Sikhism', 11=>'Zoroastrianism'],
	'referral_options' => [1=>'Via Jab Chaho Website Career Page', 2=>'Via LinkedIn Job Ad', 3=>'Via Facebook Job Ad', 8=>'Via WhatsApp Group', 4=>'Newspaper', 5=>'I know someone at Jab Chaho', 6=>'Someone at Jab Chaho Referred me', 7=>'Other'],
	'relation_options' => [1=>'Father', 2=>'Mother',3=>'Brother',4=>'Sister',5=>'Spouse',6=>'Son', 7=>'Daughter'],
	'occupation_options'=>[1=>'Employed', 2=>'Self-Employed', 3=>'Unemployed', 4=>'Retired', 5=>'Student', 6=>'House-Wife', 7=>'Other'],	
	'cities'=>[67 =>'Karachi'],
	#'cities'=>[67 =>'Karachi',86 =>'Lahore',55 =>'Islamabad',1 =>'Abbottabad',2=>'Ahmadpur East',3 =>'Astor',4=>'Attock',5=>'Awaran',6=>'Azad Jamu &amp; Kashmir (AJK)',7=>'Badin',8=>'Bahawalnagar',9=>'Bahawalpur',10=>'Bajaur Agency',11=>'Bannu',12 =>'Barkhan',13 =>'Battagram',14 =>'Bhakar city',15 =>'Bhalwal',16 =>'Bhera',17 =>'Bolan',18 =>'Buner',19 =>'Burewala',20 =>'Chaghi',21 =>'Chakwal',22 =>'Chaman',23 =>'Charsadda',24 =>'Chiniot',25 =>'Chishtian',26 =>'Chitral',27 =>'Dadu',28 =>'Daska',29 =>'Dera Bugti',30 =>'Dera Ghazi Khan',31 =>'Dera Ismail Khan',32 =>'Dera Murad Jamali',33 =>'Diamer',34 =>'Dijkot',35 =>'Dir Lower',36 =>'Dir Upper',37 =>'Duki',38 =>'Faisalabad',39 =>'Ghanche',40 =>'Ghizer',41 =>'Ghotki',42 =>'Gilgit',43 =>'Gojra',44 =>'Gujranwala',45 =>'Gujrat',46 =>'Gwadar',47 =>'Hafizabad',48 =>'Hangu',49 =>'Haripur',50 =>'Harnai',51 =>'Hassanabdal',52 =>'Hub',53 =>'Hunza',54 =>'Hyderabad',56 =>'Jacobabad',57 =>'Jafarabad',58 =>'Jaranwala',59 =>'Jhal Magsi',60 =>'Jhang',61 =>'Jhelum',62 =>'Jhumra',63 =>'Kalat',64 =>'Kamalia',65 =>'Kamoke',66 =>'Kamra',68 =>'Karak',69 =>'Kasur',70 =>'Kechh',71 =>'Khairpur',72 =>'Khanewal',73 =>'Khanpur',74 =>'Kharan',75 =>'Kharmang',76 =>'Khurrianwala',77 =>'Khushab city',78 =>'Khuzdar',79 =>'Khyber Agency',80 =>'Killa Abdullah',81 =>'Killa Sailullah',82 =>'Kohat',83 =>'Kohistan',84 =>'Kohlu',85 =>'Kot momin',87 =>'Lahri',88 =>'Laki Marwat',89 =>'Lakki Marwat',90 =>'Larkana',91 =>'Lasbela/Hub',92 =>'Lasbella',93 =>'Layyah',94 =>'Lodhran',95 =>'Loralai',96 =>'Lower Kurram Agency',97 =>'Malakand',98 =>'Mamukanja',99 =>'Mandi Bahauddin',100=>'Mansehra',101=>'Mardan',102=>'Mastung',103=>'Mianwali city',104=>'Mingora',105=>'Miranshah Agency',106=>'Mirpur',107=>'Mirpur (Kashmir)',108=>'Mirpur Khas',109=>'Mohamand Agency',110=>'Multan',111=>'Muridke',112=>'Musa Khail',113=>'Muzaffarabad',114=>'Muzaffargarh',115=>'Nagar',116=>'Narowal',117=>'Naseerabad',118=>'Nawabshah',119=>'North Waziristan',120=>'Noshero Feroz',121=>'Nowshera',122=>'Nushki',123=>'Okara',124=>'Orakzai Agency',125=>'Pakpattan',126=>'Panjgur',127=>'Parachinar Agency',128=>'Pasheen',129=>'Pasni',130=>'Peer Mehal',131=>'Peshawar',132=>'Pishin',133=>'Poonch',134=>'Quetta',135=>'Rahim Yar Khan',136=>'Rajanpur',137=>'Rawalakot',138=>'Rawalpindi',139=>'Sadiqabad',140=>'Sahiwal',141=>'Samundari',142=>'Sargodha',143=>'Satiana',144=>'Shah pur',145=>'Shangla',146=>'Sheerani',147=>'Sheikhupura',148=>'Shekhupura',149=>'Shigar',150=>'Shikarpur',151=>'Shorkot',152=>'Sialkot',153=>'Sibi',154=>'Silanwali',155=>'Skardu',156=>'Sohbatpur',157=>'Soorab (Iskanderabad)',158=>'South Waziristan',159=>'Stringer',160=>'Sukkur',161=>'Swabi',162=>'Swat',163=>'Tandlianwala',164=>'Tando Adam',165=>'Tando Alah yar',166=>'Tando Muhammad khan',167=>'Tank',168=>'Tarbela',169=>'Thatta',170=>'Thsl 18 hazari',171=>'Thsl Ahmed pur',172=>'Thsl Bhuwana',173=>'Thsl Drya Khan',174=>'Thsl esa khel',175=>'Thsl Gojra',176=>'Thsl Jaranwala',177=>'Thsl Jhumra',178=>'Thsl Kamilia',179=>'Thsl Klor kot',180=>'Thsl Lalian',181=>'Thsl Mankera',182=>'Thsl Noshehra',183=>'Thsl nurpur thal',184=>'Thsl peer mehal',185=>'Thsl pipplan',186=>'Thsl Quaidabad',187=>'Thsl Samundari',188=>'Thsl Shorkot',189=>'Thsl Tandlianwala',190=>'Toba city',191=>'Torghar',192=>'Turbat',193=>'Upper Kurram Agency',194=>'Vehari',195=>'Wah Cantonment',196=>'Washuk',197=>'Zhob',198=>'Ziarat'],
	'time_slots'=>['00:00:00' =>'12:00 AM','01:00:00' =>'01:00 AM','02:00:00' =>'02:00 AM','03:00:00' =>'03:00 AM','04:00:00' =>'04:00 AM','05:00:00' =>'05:00 AM','06:00:00' =>'06:00 AM','07:00:00' =>'07:00 AM','08:00:00' =>'08:00 AM','09:00:00' =>'09:00 AM',
	'10:00:00' =>'10:00 AM','11:00:00' =>'11:00 AM','12:00:00' =>'12:00 PM','13:00:00' =>'01:00 PM','14:00:00' =>'02:00 PM','15:00:00' =>'03:00 PM','16:00:00' =>'04:00 PM','17:00:00' =>'05:00 PM','18:00:00' =>'06:00 PM','19:00:00' =>'07:00 PM','20:00:00' =>'08:00 PM','21:00:00' =>'09:00 PM','22:00:00' =>'10:00 PM','23:00:00' =>'11:00 PM'],
	'home_page_content_pattern'=>['##NAME##'],
	'job_statuses' =>['pending_approval' => 1, 'rejected'=>2 , 'approved'=>3,'closed'=>4, 'active_jobs'=>5 ],
	'admin_user_default_action'=>[
		'logout.perform' => 'logout.perform',
		//'home.index'     => 'home.index'
	],
	'own_convenience' => [1=>'Bike',2=>'Car'],
	'previous_experience' => [1=>'1-3 years',2=>'4-5 years', 3=>'more than 5 years'],
	'applicant_status_id' => ['applied'=>1,'shortlisted'=>2,'interview_cleared'=>3,'interview_failed'=>4,'on_hold'=>5,'hired'=>6,'not_appeared'=>7,'not_shortlisted'=>8, 'interview_scheduled'=>9,'offer_declined'=>10,'interview_not_scheduled'=>11,'screening_pending'=>12,'interview_to_be_schedule'=>13,'internship_offered'=>14,'offer_accepted'=>15],
	'experience_range' =>[1=>'0 to 2 years', 2=>'3 to 5 years',3=>' 6 to 10 years',4=>'More than 10 years'],
	'experience_range_condition' => [1=>[0,2],2=>[3,5],3=>[6,10],4=>[11,200]],
	'admin_action_with_description' =>[
			'logout.perform'				 			=> 'Logout',
			'home.index'				     			=> 'Dashboard',
			'users.index'					 			=> 'Users List',
			'users.create'					 			=> 'Add User Form',
			'users.store'					 			=> 'Add User Form Submit',
			'users.show'					 			=> 'Show User',
			'users.edit'					 			=> 'Update User',
			'users.update'					 			=> 'Update User Form Submit',
			'users.destroy'					 			=> 'Delete User',
			'candidates.index'     						=> 'Candidates List',						
			'candidates.create'							=> 'Add Candidate Form',
			'candidates.store'							=> 'Add Candidate Form Submit',
			'candidates.show'							=> 'Show Candidate',
			'candidates.edit'							=> 'Update Candidate',
			'candidates.update'                         => 'Update Candidate Form Submit',
			'candidates.destroy'						=> 'Delete Candidate',
			'candidates.reviewStore'					=> 'Candidate Review Form Submit',
			'candidates.reviewDestroy'                  => 'Candidate Review Delete',
			'tips_and_guides.index'						=> 'Tips & Guides List',
			'tips_and_guides.create'					=> 'Add Tip & Guide Form',
			'tips_and_guides.store'						=> 'Add Tip & Guide Form Submit',
			'tips_and_guides.show'						=> 'Show Tip & Guide',
			'tips_and_guides.edit'						=> 'Update Tip & Guide Form',
			'tips_and_guides.update'					=> 'Update Tip & Guide Form Submit',
			'tips_and_guides.destroy'					=> 'Delete Tip & Guide',
			'shifts.index'								=> 'Shifts List',
			'shifts.create'								=> 'Add Shift Form',
			'shifts.store'								=> 'Add Shift Form Submit',
			'shifts.show'								=> 'Show Shift',
			'shifts.edit'								=> 'Update Shift',
			'shifts.update'								=> 'Update Shift Form Submit',
			'shifts.destroy'							=> 'Delete Shift',
			'area_of_interest_groups.index'				=> 'Area of Intrest Groups List',
			'area_of_interest_groups.create'			=> 'Add Area of Intrest Group Form',
			'area_of_interest_groups.store'				=> 'Add Area of Intrest Group Form Submit',
			'area_of_interest_groups.edit'				=> 'Update Area of Intrest Group Form',
			'area_of_interest_groups.update'			=> 'Update Area of Intrest Group Submit',
			'area_of_interest_groups.destroy'			=> 'Delete Area of Intrest Group',
			'area_of_interest_options.index'			=> 'Area of Intrest Options List',
			'area_of_interest_options.create'			=> 'Add Area of Intrest Option Form',
			'area_of_interest_options.store'			=> 'Add Area of Intrest Option Form Submit',
			'area_of_interest_options.edit'				=> 'Update Area of Intrest Option Form',
			'area_of_interest_options.update'			=> 'Update Area of Intrest Option Form Submit',
			'area_of_interest_options.destroy'			=> 'Delete Area of Intrest Option',
			'facility_groups.index'						=> 'Facility Groups List',
			'facility_groups.create'					=> 'Add Facility Group Form',
			'facility_groups.store'						=> 'Add Facility Group Form Submit',
			'facility_groups.edit'						=> 'Update Facility Group Form',
			'facility_groups.update'					=> 'Update Facility Group Form Submit',
			'facility_groups.destroy'					=> 'Delete Facility Group',
			'facility_options.index'					=> 'Facility Groups Options List',
			'facility_options.create'					=> 'Add Facility Option Form',
			'facility_options.store'					=> 'Add Facility Option Form Submit',
			'facility_options.edit'						=> 'Update Facility Option Form',
			'facility_options.update'					=> 'Update Facility Option Form Submit',
			'facility_options.destroy'					=> 'Delete Facility Option',
			'job_types.index'							=> 'Job Types List',
			'job_types.create'							=> 'Add Job Types Form',
			'job_types.store'							=> 'Add Job Types Form Submit',
			'job_types.show'							=> 'Show Job Type',
			'job_types.edit'							=> 'Update Job Types Form',
			'job_types.update'							=> 'Update Job Types Form Submit',
			'job_types.destroy'							=> 'Delete Job Types',
			'home_content.index'						=> 'Home Contents List',
			'home_content.create'						=> 'Add Home Content Form',
			'home_content.store'						=> 'Add Home Content Form Submit',
			'home_content.show'							=> 'Show Home Content',
			'home_content.edit'							=> 'Update Home Content Form',
			'home_content.update'						=> 'Update Home Content Form Submit',
			'home_content.destroy'						=> 'Delete Home Content',
			'cms.index'									=> 'CMS Pages List',
			'cms.create'								=> 'Add CMS Page Form',
			'cms.store'									=> 'Add CMS Page Form Submit',
			'cms.show'									=> 'Show CMS Page',
			'cms.edit'									=> 'Update CMS Page Form',
			'cms.update'								=> 'Update CMS Page Form Submit',
			'cms.destroy'								=> 'Delete CMS Page',
			'skill_sets.index'							=> 'Skill Sets List',
			'skill_sets.create'							=> 'Add Skill Set Form',
			'skill_sets.store'							=> 'Add Skill Set Form Submit',
			'skill_sets.show'							=> 'Show Skill Set',
			'skill_sets.edit'							=> 'Update Skill Set Form',
			'skill_sets.update'							=> 'Update Skill Set Form Submit',
			'skill_sets.destroy'						=> 'Delete Skill Set',
			'jobs.index'								=> 'Jobs List',
			'jobs.create'								=> 'Add Job Form',
			'jobs.store'								=> 'Add Job Form Submit',
			'jobs.show'									=> 'Show Job',
			'jobs.edit'									=> 'Update Job Form',
			'jobs.comment'								=> 'Job Comment',
			'jobs.update'								=> 'Update Job Form Submit',
			'jobs.destroy'								=> 'Delete Job',
			'applicants.index'							=> 'Applicants List',
			'applicants.show'							=> 'Applicants Show',
			'applicants.comment'						=> 'Applicants Comment',
			'job_benefits.index'						=> 'Job Benefits List',
			'job_benefits.create'						=> 'Add Job Benefit Form',
			'job_benefits.store'						=> 'Add Job Benefit Form Submit',
			'job_benefits.show'							=> 'Show Job Benefit',
			'job_benefits.edit'							=> 'Update Job Benefit Form',
			'job_benefits.update'						=> 'Update Job Benefit Form Submit',
			'job_benefits.destroy'						=> 'Delete Job Benefit',
			'roles.index'								=> 'Roles List',
			'roles.create'								=> 'Add Role Form',
			'roles.store'								=> 'Add Role Form Submit',
			'roles.show'								=> 'Show Role',
			'roles.edit'								=> 'Update Role Form',
			'roles.update'								=> 'Update Role Form Submit',
			'roles.destroy'								=> 'Delete Role',
			'permissions.index'							=> 'Permissions List',
			'permissions.create'						=> 'Add Permission Form',
			'permissions.store'							=> 'Add Permission Form Submit',
			'permissions.show'							=> 'Show Permission',
			'permissions.edit'							=> 'Update Permission Form',
			'permissions.update'						=> 'Update Permission Form Submit',
			'permissions.destroy'						=> 'Delete Permission',
			'candidates.phoneConversationStore'			=> 'Candidate Phone Conversation Form Submit',
			'candidates.phoneConversationDestroy'		=> 'Candidate Phone Conversation Delete',
			'candidates.scheduleStore'					=> 'Candidate Schedule Form Submit',
			'candidates.scheduleDestroy'				=> 'Candidate Schedule Delete',
			'applicants.commentDestroy' 				=> 'Applicant Comment Delete',
			'jobs.commentDestroy'						=> 'Job Comment Delete',
			'jobs.graph.data'							=> 'Dashboard Jobs Graph Data',
			'get.count.data'							=> 'Dashboard widget Counts',
			'candidates.referred.index'					=> 'Referred candidates List',
			'candidates.referred.show'					=> 'Referred Candidate Show',
			'jobs.graph.data'							=> 'Dashboard Jobs Graph Data',
			'candidate.document.delete'					=> 'Candidate Documents Delete',
			'candidate.portfolio.delete'				=> 'Candidate Portfolios Delete'
	],
	'countries' => [
		'AF' => 'Afghanistan',
		'AX' => 'Aland Islands',
		'AL' => 'Albania',
		'DZ' => 'Algeria',
		'AS' => 'American Samoa',
		'AD' => 'Andorra',
		'AO' => 'Angola',
		'AI' => 'Anguilla',
		'AQ' => 'Antarctica',
		'AG' => 'Antigua And Barbuda',
		'AR' => 'Argentina',
		'AM' => 'Armenia',
		'AW' => 'Aruba',
		'AU' => 'Australia',
		'AT' => 'Austria',
		'AZ' => 'Azerbaijan',
		'BS' => 'Bahamas',
		'BH' => 'Bahrain',
		'BD' => 'Bangladesh',
		'BB' => 'Barbados',
		'BY' => 'Belarus',
		'BE' => 'Belgium',
		'BZ' => 'Belize',
		'BJ' => 'Benin',
		'BM' => 'Bermuda',
		'BT' => 'Bhutan',
		'BO' => 'Bolivia',
		'BA' => 'Bosnia And Herzegovina',
		'BW' => 'Botswana',
		'BV' => 'Bouvet Island',
		'BR' => 'Brazil',
		'IO' => 'British Indian Ocean Territory',
		'BN' => 'Brunei Darussalam',
		'BG' => 'Bulgaria',
		'BF' => 'Burkina Faso',
		'BI' => 'Burundi',
		'KH' => 'Cambodia',
		'CM' => 'Cameroon',
		'CA' => 'Canada',
		'CV' => 'Cape Verde',
		'KY' => 'Cayman Islands',
		'CF' => 'Central African Republic',
		'TD' => 'Chad',
		'CL' => 'Chile',
		'CN' => 'China',
		'CX' => 'Christmas Island',
		'CC' => 'Cocos (Keeling) Islands',
		'CO' => 'Colombia',
		'KM' => 'Comoros',
		'CG' => 'Congo',
		'CD' => 'Congo, Democratic Republic',
		'CK' => 'Cook Islands',
		'CR' => 'Costa Rica',
		'CI' => 'Cote D\'Ivoire',
		'HR' => 'Croatia',
		'CU' => 'Cuba',
		'CY' => 'Cyprus',
		'CZ' => 'Czech Republic',
		'DK' => 'Denmark',
		'DJ' => 'Djibouti',
		'DM' => 'Dominica',
		'DO' => 'Dominican Republic',
		'EC' => 'Ecuador',
		'EG' => 'Egypt',
		'SV' => 'El Salvador',
		'GQ' => 'Equatorial Guinea',
		'ER' => 'Eritrea',
		'EE' => 'Estonia',
		'ET' => 'Ethiopia',
		'FK' => 'Falkland Islands (Malvinas)',
		'FO' => 'Faroe Islands',
		'FJ' => 'Fiji',
		'FI' => 'Finland',
		'FR' => 'France',
		'GF' => 'French Guiana',
		'PF' => 'French Polynesia',
		'TF' => 'French Southern Territories',
		'GA' => 'Gabon',
		'GM' => 'Gambia',
		'GE' => 'Georgia',
		'DE' => 'Germany',
		'GH' => 'Ghana',
		'GI' => 'Gibraltar',
		'GR' => 'Greece',
		'GL' => 'Greenland',
		'GD' => 'Grenada',
		'GP' => 'Guadeloupe',
		'GU' => 'Guam',
		'GT' => 'Guatemala',
		'GG' => 'Guernsey',
		'GN' => 'Guinea',
		'GW' => 'Guinea-Bissau',
		'GY' => 'Guyana',
		'HT' => 'Haiti',
		'HM' => 'Heard Island & Mcdonald Islands',
		'VA' => 'Holy See (Vatican City State)',
		'HN' => 'Honduras',
		'HK' => 'Hong Kong',
		'HU' => 'Hungary',
		'IS' => 'Iceland',
		'IN' => 'India',
		'ID' => 'Indonesia',
		'IR' => 'Iran, Islamic Republic Of',
		'IQ' => 'Iraq',
		'IE' => 'Ireland',
		'IM' => 'Isle Of Man',
		'IL' => 'Israel',
		'IT' => 'Italy',
		'JM' => 'Jamaica',
		'JP' => 'Japan',
		'JE' => 'Jersey',
		'JO' => 'Jordan',
		'KZ' => 'Kazakhstan',
		'KE' => 'Kenya',
		'KI' => 'Kiribati',
		'KR' => 'Korea',
		'KW' => 'Kuwait',
		'KG' => 'Kyrgyzstan',
		'LA' => 'Lao People\'s Democratic Republic',
		'LV' => 'Latvia',
		'LB' => 'Lebanon',
		'LS' => 'Lesotho',
		'LR' => 'Liberia',
		'LY' => 'Libyan Arab Jamahiriya',
		'LI' => 'Liechtenstein',
		'LT' => 'Lithuania',
		'LU' => 'Luxembourg',
		'MO' => 'Macao',
		'MK' => 'Macedonia',
		'MG' => 'Madagascar',
		'MW' => 'Malawi',
		'MY' => 'Malaysia',
		'MV' => 'Maldives',
		'ML' => 'Mali',
		'MT' => 'Malta',
		'MH' => 'Marshall Islands',
		'MQ' => 'Martinique',
		'MR' => 'Mauritania',
		'MU' => 'Mauritius',
		'YT' => 'Mayotte',
		'MX' => 'Mexico',
		'FM' => 'Micronesia, Federated States Of',
		'MD' => 'Moldova',
		'MC' => 'Monaco',
		'MN' => 'Mongolia',
		'ME' => 'Montenegro',
		'MS' => 'Montserrat',
		'MA' => 'Morocco',
		'MZ' => 'Mozambique',
		'MM' => 'Myanmar',
		'NA' => 'Namibia',
		'NR' => 'Nauru',
		'NP' => 'Nepal',
		'NL' => 'Netherlands',
		'AN' => 'Netherlands Antilles',
		'NC' => 'New Caledonia',
		'NZ' => 'New Zealand',
		'NI' => 'Nicaragua',
		'NE' => 'Niger',
		'NG' => 'Nigeria',
		'NU' => 'Niue',
		'NF' => 'Norfolk Island',
		'MP' => 'Northern Mariana Islands',
		'NO' => 'Norway',
		'OM' => 'Oman',
		'PK' => 'Pakistan',
		'PW' => 'Palau',
		'PS' => 'Palestinian Territory, Occupied',
		'PA' => 'Panama',
		'PG' => 'Papua New Guinea',
		'PY' => 'Paraguay',
		'PE' => 'Peru',
		'PH' => 'Philippines',
		'PN' => 'Pitcairn',
		'PL' => 'Poland',
		'PT' => 'Portugal',
		'PR' => 'Puerto Rico',
		'QA' => 'Qatar',
		'RE' => 'Reunion',
		'RO' => 'Romania',
		'RU' => 'Russian Federation',
		'RW' => 'Rwanda',
		'BL' => 'Saint Barthelemy',
		'SH' => 'Saint Helena',
		'KN' => 'Saint Kitts And Nevis',
		'LC' => 'Saint Lucia',
		'MF' => 'Saint Martin',
		'PM' => 'Saint Pierre And Miquelon',
		'VC' => 'Saint Vincent And Grenadines',
		'WS' => 'Samoa',
		'SM' => 'San Marino',
		'ST' => 'Sao Tome And Principe',
		'SA' => 'Saudi Arabia',
		'SN' => 'Senegal',
		'RS' => 'Serbia',
		'SC' => 'Seychelles',
		'SL' => 'Sierra Leone',
		'SG' => 'Singapore',
		'SK' => 'Slovakia',
		'SI' => 'Slovenia',
		'SB' => 'Solomon Islands',
		'SO' => 'Somalia',
		'ZA' => 'South Africa',
		'GS' => 'South Georgia And Sandwich Isl.',
		'ES' => 'Spain',
		'LK' => 'Sri Lanka',
		'SD' => 'Sudan',
		'SR' => 'Suriname',
		'SJ' => 'Svalbard And Jan Mayen',
		'SZ' => 'Swaziland',
		'SE' => 'Sweden',
		'CH' => 'Switzerland',
		'SY' => 'Syrian Arab Republic',
		'TW' => 'Taiwan',
		'TJ' => 'Tajikistan',
		'TZ' => 'Tanzania',
		'TH' => 'Thailand',
		'TL' => 'Timor-Leste',
		'TG' => 'Togo',
		'TK' => 'Tokelau',
		'TO' => 'Tonga',
		'TT' => 'Trinidad And Tobago',
		'TN' => 'Tunisia',
		'TR' => 'Turkey',
		'TM' => 'Turkmenistan',
		'TC' => 'Turks And Caicos Islands',
		'TV' => 'Tuvalu',
		'UG' => 'Uganda',
		'UA' => 'Ukraine',
		'AE' => 'United Arab Emirates',
		'GB' => 'United Kingdom',
		'US' => 'United States',
		'UM' => 'United States Outlying Islands',
		'UY' => 'Uruguay',
		'UZ' => 'Uzbekistan',
		'VU' => 'Vanuatu',
		'VE' => 'Venezuela',
		'VN' => 'Viet Nam',
		'VG' => 'Virgin Islands, British',
		'VI' => 'Virgin Islands, U.S.',
		'WF' => 'Wallis And Futuna',
		'EH' => 'Western Sahara',
		'YE' => 'Yemen',
		'ZM' => 'Zambia',
		'ZW' => 'Zimbabwe',
	],
	'job_limit' => 5,
];